"""Configure the password gateway on a specific internal address; firewall unchanged."""
import argparse
import ipaddress
import json
from pathlib import Path
import shutil

from pilot_users import render


def configure(root, address, clients):
    ip = ipaddress.IPv4Address(address)
    networks = [ipaddress.IPv4Network(value, strict=True)
                for value in ([clients] if isinstance(clients, str) else clients)]
    private_ranges = [ipaddress.IPv4Network(cidr) for cidr in
                      ('10.0.0.0/8', '172.16.0.0/12', '192.168.0.0/16')]
    if not any(ip in block for block in private_ranges):
        raise ValueError('Choose the RFC1918 address of the shared PC.')
    if not networks or not all(any(network.subnet_of(block) for block in private_ranges)
                               for network in networks):
        raise ValueError('Choose the internal subnet containing pilot clients.')
    pilot = root / 'runtime/pilot'
    if not (pilot / 'compose.yml').is_file():
        raise RuntimeError('Install the pilot password gateway first.')
    settings = {'address': str(ip), 'client_cidr': str(networks[0]),
                'client_addresses': [str(network) for network in networks], 'port': 13010,
                'url': f'http://{ip}:13010'}
    (root / 'runtime/lan.json').write_text(json.dumps(settings, indent=2) + '\n', encoding='utf-8')
    (pilot / 'compose.lan.yml').write_text(
        '# Generated by configure_lan.py; only the password gateway is shared.\n'
        'services:\n  pilot-gateway:\n    restart: unless-stopped\n    ports: !override\n'
        '      - "127.0.0.1:13010:8080"\n'
        f'      - "{ip}:13010:8080"\n', encoding='utf-8')
    source = Path(__file__).resolve().parent
    for name in ('Pilot.ps1', 'Enable-LanFirewall.ps1', 'check_pilot.py'):
        if (source / name).resolve() != (root / name).resolve():
            shutil.copy2(source / name, root / name)
    render(root)
    print(f'LAN gateway prepared: {settings["url"]}. Password retained. Firewall unchanged.')


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--deployment-root', type=Path, default=Path('C:/ProgramData/BOM-Supabase'))
    parser.add_argument('--address', required=True)
    parser.add_argument('--clients', required=True, nargs='+', help='Internal client subnets in CIDR notation')
    args = parser.parse_args()
    configure(args.deployment_root.resolve(), args.address, args.clients)
