"""S5 -- emit the TCB data dictionary as markdown from the S1 profile."""

import pandas as pd

from common import OUT, ROOT

prof = pd.read_csv(OUT / "s1_column_profile_tcb.csv")

ORDER = {"INPUT": 0, "INPUT/SENSITIVE": 1, "CANDIDATE": 2, "OUTPUT": 3, "MEMORY": 4}
prof["ord"] = prof["prd_class"].map(ORDER).fillna(9)


def usable(r):
    if r.fill_pct == 0:
        return "EMPTY - drop"
    if r.fill_pct < 15:
        return "unusable as a feature"
    if r.fill_pct < 60:
        return "sparse - impute or gate"
    if r.type == "constant":
        return "constant - no signal"
    return "usable"


prof["verdict"] = prof.apply(usable, axis=1)

lines = [
    "# Data Dictionary - BOM Review Jan'26, TCB module",
    "",
    "Auto-generated by `analysis/s5_datadict.py` from `BOM table/BOM REVIEW_Jan'26 .csv`.",
    "Scope: `module = TCB`, 2,780 rows of a 17,165-row / 116-column extract.",
    "",
    "`prd_class` follows PRD section 5.1. **OUTPUT** and **MEMORY** columns must never be used as",
    "ML inputs (target leakage). **CANDIDATE** columns are inputs, not truth.",
    "",
    "`verdict` is a feature-engineering judgement based on fill rate and variance in the TCB subset only.",
    "",
    "## Glossary",
    "",
    "### Confirmed",
    "",
    "| Term | Meaning | Where it appears |",
    "|---|---|---|",
    "| **ROP** | **Reorder point** - the stock level at which replenishment is triggered "
    "(confirmed by process owner, 28 Jul 2026) | `rop_qty`, `factory_recommended_new_rop`, "
    "`sfm_rop`, `sfm_brr_rop`, `atm_recommended_rop`, `recom_rop`, `one_msia_rop`, `rop_adoption`, `rop_delta` |",
    "| **Max** | Maximum stock level - the replenish-up-to ceiling | `max_qty`, "
    "`factory_recommended_new_max`, and the `*_max` candidate columns |",
    "| **Min** | Minimum stock level - the floor below which stock should not fall | `min_qty`, "
    "`factory_recommended_new_min`, and the `*_min` candidate columns |",
    "| **CLT** | Contractual lead time, in days | `contractual_lead_time`, `new_clt_change_type`, `sfm_mean_lt_cd` |",
    "| **PO** | Purchase order | `open_po_qty` |",
    "| **SFM** | The name of the incumbent recommendation algorithm. **Not an acronym - there is no "
    "expansion to look up** (confirmed by process owner, 28 Jul 2026). Emits "
    "`Increase Algo` / `Maintain Algo` / `Decrease Algo` | `sfm_recommendation`, `sfm_max/rop/min`, "
    "`sfm_brr_*`, `sfm_criticality`, `sfm_mean_lt_cd`, `rop_1dlt_sfm` |",
    "",
    "The Max / ROP / Min triple is the stocking parameter set this whole system exists to review;",
    "the engine must always preserve `max >= rop >= min` (PRD section 6.1).",
    "",
    "### Unresolved - confirm with the process / WINGS owner before relying on these",
    "",
    "| Term | Status |",
    "|---|---|",
    "| **BRR** | Always paired as \"SFM/BRR\" in the adoption labels. `sfm_brr_*` is 100% populated "
    "while `sfm_*` is only 23.6%, so BRR is likely the operative variant. May, like SFM, simply be "
    "an algorithm name rather than an acronym |",
    "| **ATM** | A candidate recommendation source. `atm_recommended_max` reproduces the approved "
    "value on 82.6% of rows - the strongest single predictor in the file |",
    "| **DSV** | Structured shorthand used by engineers in `comments` (e.g. `DSV:3a, min(sfm,current)`). "
    "Possibly an existing decision-step taxonomy; owner to confirm |",
    "| **OOQ** | Appears only in `ooq_adoption` (0.3% filled) |",
    "| **DOI** | Appears in `avail_doi_maxd`, `uzb_doi_group2`. Conventionally 'days of inventory', unconfirmed here |",
    "| **EOH** | Appears in `qry_eoh_excess_qty`. Conventionally 'end on hand', unconfirmed here |",
    "| **UZB / ATK / IPN / SIMS / PSI / DS / DP** | Undefined in both the PRD and the data |",
    "",
]

for cls in sorted(prof["prd_class"].unique(), key=lambda c: ORDER.get(c, 9)):
    sub = prof[prof["prd_class"] == cls].sort_values("fill_pct", ascending=False)
    lines += [f"## {cls} ({len(sub)} columns)", "",
              "| column | fill % | distinct | type | range / top values | verdict |",
              "|---|---:|---:|---|---|---|"]
    for _, r in sub.iterrows():
        if r.type == "numeric" and pd.notna(r.get("min")):
            detail = f"min {r['min']:g} / p50 {r['p50']:g} / p95 {r['p95']:g} / max {r['max']:g}"
            if pd.notna(r.get("n_negative")) and r["n_negative"] > 0:
                detail += f" — **{int(r['n_negative'])} negative**"
        else:
            detail = str(r.get("top_values", "") or "")[:110]
        detail = detail.replace("|", "\\|")
        lines.append(f"| `{r['column']}` | {r['fill_pct']} | {r['n_unique']} | {r['type']} | {detail} | {r['verdict']} |")
    lines.append("")

dest = ROOT / "docs" / "Data_Dictionary_TCB_Jan26.md"
dest.write_text("\n".join(lines), encoding="utf-8")
print(f"wrote {dest}  ({len(lines)} lines)")
print(prof.groupby(["prd_class", "verdict"]).size().to_string())
